# The rest of my fun git aliases
alias gl='git log'
alias gf='git fetch --all --prune'
alias grom='git rebase $(git symbolic-ref --short refs/remotes/origin/HEAD)'
alias gprune='master=$(basename $(git symbolic-ref --short refs/remotes/origin/HEAD)); git branch --merged $master | grep -v "${master}$" | xargs git branch -d'
alias gsgr='git stash && git fetch && git rebase $(git symbolic-ref --short refs/remotes/origin/HEAD) && git stash pop'
alias gcan='git commit -a --amend --no-edit'

alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gco='git checkout'
alias gcb='git copy-branch-name'
alias gb='git branch'
alias gba='git branch -a'
alias gs='git status'
alias gac='git add -A && git commit -m'
alias ge='git-edit-new'
